### ISSUE TITLE
$dateCreated must not be accessed before initialization

### ISSUE THREAD

**Issue by thiagarajanm** [putyourlightson/craft-entry-count#32] opened 2022-10-30 20:08 UTC
Facing the issue after updating to the latest craft version

Error: Typed property putyourlightson\entrycount\models\EntryCountModel::$dateCreated must not be accessed before initialization

Craftcms Version: 4.3.1

I initialized the dateCreated and dateUpdated value in the models and it works.

**Comment by bencroker** [comment] 2022-10-30 21:31
Fixed in https://github.com/putyourlightson/craft-entry-count/commit/ea952353a2baf6483ee72a372082d9cc71b5dc57 and released in version 3.0.1. This was caused by a [breaking change](https://github.com/yiisoft/yii2/issues/19546#issuecomment-1291280606) in Yii 2.0.46.

**Closed as completed by bencroker** 2022-10-30 21:31 UTC
